### PR TITLE
Guzzle Client Middleware Fixes

### PR DESCRIPTION
**Pull request by brandinarsenault**
Due to the changes made in #121 we broke the library in v5.0. These changes are to resolve this. I've tested it against the API with Auth. Still need to do some more testing to make sure this resolved it entirely.

### CODE REVIEW

**Comment by brandinarsenault** [comment]
@echosa could you look over this and give me your thoughts?

**Comment by brandinarsenault** [comment]
The code here is mostly bugfixes and gets the library working for 5.0. I'll merge this and if you have any comments, we can do another PR to do some cleanup!

**Comment by brandinarsenault** [comment]
Scratch that! I can't bypass the review requirement :)

**Review by echosa — APPROVED** [review]
:+1: from me

**Comment by ThibaultVlacich** [comment]
@brandinarsenault Don't forget to revert the changes I made in the Readme in #121. The example code in the Readme right now are not working anymore with the changes made here :)

**Pull request merged**
