### PR TITLE
README Updates

### PR DESCRIPTION
**Pull request by brandinarsenault**
Some updates to the README to pretty it up and add some more details :)

### CODE REVIEW

**Comment by brandinarsenault** [comment]
@nicklaw5 @echosa Here's a preview of the new README:
https://github.com/brandinarsenault/twitch-api-php

**Review by nicklaw5 — APPROVED** [review]
LGTM

**Comment by brandinarsenault** [comment]
@echosa going to merge this, if theres anything else you'd like us to add, just shoot up a new issue I'll be happy to do it!

**Comment by echosa** [comment]
Excellent! Thanks for this. Seems much friendlier and more useful now!

**Pull request merged**
