### PR TITLE
Update New API Endpoints to force bearer token

### PR DESCRIPTION
**Pull request by brandinarsenault**
- Updated CallApi function to force bearer
- Endpoints from all classes were updated to force bearer token

### CODE REVIEW

**Comment by nicklaw5** [comment]
I probably won't be able to take a look until the weekend. Unless @echosa has time before then.

**Comment by echosa** [comment]
I'll try to get to this as soon as I can.

**Comment by echosa** [comment]
Hoo boy. Just tried to take a quick stab at this, but just getting tests to run took too long. I tried to `vendor/bin/phpunit`, but needed to `composer install` first. However:

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for friendsofphp/php-cs-fixer v2.13.1 -> satisfiable by friendsofphp/php-cs-fixer[v2.13.1].
    - friendsofphp/php-cs-fixer v2.13.1 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.3) does not satisfy that requirement.
  Problem 2
    - Installation request for phpspec/phpspec 5.1.0 -> satisfiable by phpspec/phpspec[5.1.0].
    - phpspec/phpspec 5.1.0 requires php ^7.1, <7.4 -> your PHP version (7.4.3) does not satisfy that requirement.
```

Ok, maybe composer needs to be updated?

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpspec/phpspec 5.1.2 requires php ^7.1, <7.4 -> your PHP version (7.4.3) does not satisfy that requirement.
    - phpspec/phpspec 5.1.1 requires php ^7.1, <7.4 -> your PHP version (7.4.3) does not satisfy that requirement.
    - phpspec/phpspec 5.1.0 requires php ^7.1, <7.4 -> your PHP version (7.4.3) does not satisfy that requirement.
    - Installation request for phpspec/phpspec ^5.1 -> satisfiable by phpspec/phpspec[5.1.0, 5.1.1, 5.1.2].
```

Ok, then. `phpspec` and `phpunit` need to be updated to work with PHP 7.4. No problem, right? Let's just get ourselves up-to-date and grab the latest versions.

```
        "phpspec/phpspec": "^6.1",
        "phpunit/phpunit": "^9.2"
```

Cool, cool. Now we just need to update again...

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit ^9.2 -> satisfiable by phpunit/phpunit[9.2.0, 9.2.1, 9.2.2].
    - Can only install one of: sebastian/exporter[4.0.0, 1.0.0].
    - Can only install one of: sebastian/exporter[4.0.0, 1.0.1].
    - Can only install one of: sebastian/exporter[4.0.0, 1.0.2].
    - Can only install one of: sebastian/exporter[4.0.0, 1.1.0].
    - Can only install one of: sebastian/exporter[4.0.0, 1.2.0].
    - Can only install one of: sebastian/exporter[4.0.0, 1.2.1].
    - Can only install one of: sebastian/exporter[4.0.0, 1.2.2].
    - Can only install one of: sebastian/exporter[4.0.0, 2.0.0].
    - Can only install one of: sebastian/exporter[4.0.0, 3.0.0].
    - Can only install one of: sebastian/exporter[4.0.0, 3.1.0].
    - Can only install one of: sebastian/exporter[4.0.0, 3.1.1].
    - Can only install one of: sebastian/exporter[4.0.0, 3.1.2].
    - Conclusion: don't install sebastian/exporter 4.0.0|don't install phpspec/phpspec 6.1.1
    - Conclusion: install sebastian/exporter 4.0.0
    - phpspec/phpspec 6.1.0 requires sebastian/exporter ^1.0 || ^2.0 || ^3.0 -> satisfiable by sebastian/exporter[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 2.0.0, 3.0.0, 3.1.0, 3.1.1, 3.1.2].
    - Installation request for phpspec/phpspec ^6.1 -> satisfiable by phpspec/phpspec[6.1.0, 6.1.1].
```

Ok. So, apparently PHPUnit 9 changed bumped the `sebastian/exporter` dependency to 4.0, but that's having issues. Again, no worries. Let's just use PHPUnit 8 instead.

```
        "phpunit/phpunit": "^8.5"
```

Will composer update finish this time?

```
$ composer update
[...]
Writing lock file
Generating autoload files
```

Sweet! Now let's just run the tests!

```
$ vendor/bin/phpunit 
PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in /home/echosa/dev/chess.com/twitch-api-php/test/NewTwitchApi/Resources/UsersTest.php:15
Stack trace:
#0 /home/echosa/dev/chess.com/twitch-api-php/vendor/phpunit/phpunit/src/Util/FileLoader.php(59): include_once()
#1 /home/echosa/dev/chess.com/twitch-api-php/vendor/phpunit/phpunit/src/Util/FileLoader.php(47): PHPUnit\Util\FileLoader::load()
#2 /home/echosa/dev/chess.com/twitch-api-php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(354): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /home/echosa/dev/chess.com/twitch-api-php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(452): PHPUnit\Framework\TestSuite->addTestFile()
#4 /home/echosa/dev/chess.com/twitch-api-php/vendor/phpunit/phpunit/src/Util/Configuration.php(1005): PHPUnit\Framework\TestSuite->addTestFiles()
#5 /home/echosa/dev/chess.com/twitch-api-php/vendor/phpunit/phpunit/src/Util/Configuration.php(874): PHPUnit\Util\Configuration->getTestSuite()
#6 /home/echosa/dev/chess.com/twitch-api-p in /home/echosa/dev/chess.com/twitch-api-php/test/NewTwitchApi/Resources/UsersTest.php on line 15
```

Oh... right.... PHPUnit 6 changed from the old `PHPUnit_Framework_TestCase` to the new, properly namespaced `PHPUnit\Framework\TestCase`. Let's just see what all we need to update.

```
 $ ag PHPUnit_Framework_TestCase
test/NewTwitchApi/Resources/UsersTest.php
13:use PHPUnit_Framework_TestCase;
15:class UsersTest extends PHPUnit_Framework_TestCase
```

Whew. Just the one test class. Easy enough.

```
[... editing the test class ...]
use PHPUnit\Framework\TestCase;
[...]
class UsersTest extends TestCase
[...]
```

:crossed_fingers: Let's try tests again...

```
$ vendor/bin/phpunit 
PHPUnit 8.5.5 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 5:
  - Element 'testsuite': The attribute 'name' is required but missing.

  Test results may not be as expected.


EE.......                                                           9 / 9 (100%)

Time: 523 ms, Memory: 6.00 MB

There were 2 errors:

1) NewTwitchApi\Tests\Resources\UsersTest::testGetUserByIdShouldReturnSuccessfulResponseWithUserData
GuzzleHttp\Exception\RequestException: Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

Whew. Finally got to the point where we have an expected failure (I hope). :-P 

I've used up too much of my work day already looking into this. Maybe this will help one of you to continue working on this. Otherwise, as I said before, I'll get to it when I can. 

We'll need to get these composer changes in place. Maybe that should be a separate PR that this PR can merge in once the changes are in place? Thoughts?

**Comment by echosa** [comment]
I went ahead and created #61 for updating to PHP7.4 support and fixing composer

**Comment by brandinarsenault** [comment]
I looked at your build log @echosa and the two failures are 400 Bad Request returns due to Client ID. What is the best and most suitable way of storing a Client ID for testing? Can we add it into TravisCI so it doesn't get exposed? We'll need the Client Secret too as this is required to get the App Token, which would resolve this issue. 

`Client error: `POST https://id.twitch.tv/oauth2/token` resulted in a `400 Bad Request` response:
{"status":400,"message":"invalid client"}`

**Comment by echosa** [comment]
I know next to nothing about Travis CI. @nicklaw5 set all that up well before I became co-mainatiner here.

**Comment by echosa** [comment]
@brandinarsenault #61 has been merged. Please update this branch. :-)

**Comment by nicklaw5** [comment]
All Travis CI is doing is calling `make test`, which you can do locally also. It simply calls `make test` on multiple versions of PHP to validate those versions are still supported. There is no special sauce.

Happy to consider other CI tools if you have a preference. GitHub Actions may be more suitable now, and it will allow others to manage the CI workflow rather than just myself.

As far as I can see, the mock that we're using may not be working, which means its trying to actually hit the Twitch API. I feel we need to refactor our tests.

@brandinarsenault please rebase you branch onto master to pull in the changes from #61 and make a best-effort approach to resolving tests. If you're unable to resolve the tests, I'm happy to merge the PR and either @echosa or myself can resolve the tests in a separate PR. Mind you we won't be releasing a new version until tests resolve.

**Comment by brandinarsenault** [comment]
Hi guys,

Rebased as requested as you can see above. It continues to fail due to the 400 Bad Request returns. I have no preference in CI tools, I genuinely have never used them so my knowledge on them is lacking greatly. What seems likely, is if we were to add environment variables to Travis CI, we would be able to use those in the test script (so that way the Client ID and Client Secret don't get exposed) to get the application key and in turn, use that in the tests. I honestly think hitting the API to test the results is fine, it makes sure that things *are* actually working. 

@nicklaw5 would you be opposed to adding two environment variables to the Travis CI? You would generate the Client ID and Secret for it on the Twitch Dev Console

Dev Console: https://dev.twitch.tv/console
Travis CI Environment Variables: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

Now to use those variables...I still don't know, but at the very least, once they're added I can begin refactoring the tests to try to get this to succeed 

Looking forward to the reply,
Brandin.

**Comment by nicklaw5** [comment]
> @nicklaw5 would you be opposed to adding two environment variables to the Travis CI? You would generate the Client ID and Secret for it on the Twitch Dev Console

To be honest, I don't want to support integration tests. They are unnecessary for a library of this nature. And again we come back to the issue where I am the only person that has access to removing/replacing the tokens as I am the only one able to access Travis CI.

We simply need to refactor the unit tests. Not a lot of work really. I already started looking at it yesterday.

If you're done making changes, and if @echosa supports it also, I'm happy to merge in its current state.

**Comment by brandinarsenault** [comment]
All changes are final and complete, only thing that needs adjusting is the unit tests - ready for merge.

**Comment by echosa** [comment]
I agree. We should avoid integration tests, and fix the existing tests/mocks. 

If @brandinarsenault needs these changes ASAP, we can merge, fix the tests, wait to create a release until the tests are fixed, and in the meantime anyone who needs can point their composer to master.

If the changes are not needed ASAP, then I'd prefer not to merge code with failing tests.

**Comment by brandinarsenault** [comment]
Hi guys - any progress from either of you on this? I'm curious to what you envision the adjustments to the tests being? If they're not actually calling the API in the test, I guess I'm curious what we would even be testing for? I suppose just general PHP errors?

Twitch released a range of new endpoints today I want to PR immediately, but I want to do it after this is merged so we keep them on their own and on the new code base.

**Comment by echosa** [comment]
@brandinarsenault I just took a stab at this, and simply replacing the `$appAccessToken` variables in `UsersTest.php` with a string was enough to get the tests to pass. This keeps the test from actually hitting the API, which is what we want, but still tests our handling of a set, expected JSON response from Twitch.

If you make this same change, then this PR should pass TravisCI. I'm able to reproduce by running the tests locally.

**Comment by echosa** [comment]
Also, please use the provided git hook. Instructions are in the readme. :-)

**Comment by brandinarsenault** [comment]
No dice on the git hook - looks like the pre-commit hook is written for Linux, I'm on Windows using Atom. I tried to work with it but not the best success, I'll try to resolve it for the future, however. Hopefully, this push works and we can move forward with merging. I request a hold on a version while I complete the PR for the new Endpoints, shouldn't be long.

**Comment by brandinarsenault** [comment]
Okay back at a loss - the first build after I pushed changes to UserTest.php returned fails from the Spec's because they weren't updated, okay, no problem, included them all to have a fake bearer token and I get this:
`      exception [err:TypeError("Return value of NewTwitchApi\Resources\AbstractResource::callApi() must implement interface Psr\Http\Message\ResponseInterface, null returned")] has been thrown.
`
I'm not certain where to proceed to get this build to succeed.

**Comment by echosa** [comment]
I see that error, too. Locally and on TravisCI. Looking into it now.

**Comment by echosa** [comment]
@brandinarsenault I found the issue. The spec is expecting a `Request` object that is instantiated with only method and URI. 

https://github.com/brandinarsenault/twitch-api-php/blob/6378bce65dd5c798a34750ef0fdf202441b55c28/spec/NewTwitchApi/Resources/GamesApiSpec.php#L20

However, now the headers need to be specified, since the bearer is being used.

You'll need to change the lines in the specs that set up the Guzzle response. They currently look like this (using the first example PHPSpec runs):

```
 $guzzleClient->send(new Request('GET', 'games?id=12345&id=98765'))->willReturn($response);
$this->getGames('TEST_TOKEN, ['12345','98765'])->shouldBeAnInstanceOf(ResponseInterface::class);
```

but they should include the headers, like this:

```
$guzzleClient->send(new Request('GET', 'games?id=12345&id=98765', ['Authorization' => 'Bearer TEST_TOKEN']))->willReturn($response);
$this->getGames("TEST_TOKEN", ['12345','98765'])->shouldBeAnInstanceOf(ResponseInterface::class);
```

With this change, the Prophecy `Guzzle` object will now expect the correct `Request` object be passed into it and therefore will return the given `$response`. As it is now, the `Guzzle` object isn't returning anything, because it's currently only set up to expect the previous, incorrect `Request` object (which it never receives, therefore it doesn't return `$response`).

I'm really glad to know the specs are doing their job. :-)

**Comment by brandinarsenault** [comment]
Holy crap it worked, I am going to celebrate...please review changes and merge PR. As requested, hold off on a new version while I PR the new Endpoints

**Comment by echosa** [comment]
Good enough for me! There's some cleanup I'd like that I'll do later. This is good enough for me. I'll merge, and then you can work on the other endpoints. Thanks!

> I request a hold on a version while I complete the PR for the new Endpoints, shouldn't be long.

I'm happy to wait before releasing the next version. It'll be a major version bump!

**Comment by nicklaw5** [comment]
Good work folks :clap: 

Sorry, I wasn't able to assist. It's been a busy week for me.

**Pull request merged**
