### PR TITLE
Update composer.json for PHP 7.4

### PR DESCRIPTION
**Pull request by echosa**
As discovered in https://github.com/nicklaw5/twitch-api-php/pull/60#issuecomment-642774007 this library doesn't currently work with PHP 7.4. This PR does what I believe to be the bare minimum to fix that.

Relates to #60

### CODE REVIEW

**Comment by nicklaw5** [comment]
So that actually not going to work. phpunit v8 requires PHP 7.3 or higher, which means we lose support for 7.1 and 7.2 and that is not ideal.

I'll take a closer look at a better solution.

**Comment by nicklaw5** [comment]
Unfortunately, we need to drop support for PHP 7.1 if we want support for 7.4. I've added a commit to this PR to that effect.

It does mean we have to bump this library to v3 as well.

**Comment by nicklaw5** [comment]
@echosa Any thoughts before I merge this?

**Comment by echosa** [comment]
> It does mean we have to bump this library to v3 as well.

I already planned on doing that, since #60 adds breaking changes. So I'm fine with that. 

> Any thoughts before I merge this?

Seems fine. Why does 7.1 need to be dropped? I'm perfectly fine with dropping it. I'd just like to learn why it's necessary here. :-)

**Comment by nicklaw5** [comment]
> Why does 7.1 need to be dropped?

Because phpunit v8.x only supports PHP 7.2 or higher. And if we were to use phpunit v7.x, it only supports up to PHP 7.3.

**Pull request merged**
